### PR TITLE
Add support for Laravel 7

### PR DESCRIPTION
**Pull request by owenvoke**
Add support for the upcoming Laravel 7 release.

### CODE REVIEW

**Review by nunomaduro — APPROVED** [review]

**Comment by hmazter** [comment]
Thanks for your contribution. I think we need to update the build matrix to add Laravel 7.* to the matrix.
Will you do it?
https://github.com/hmazter/laravel-schedule-list/blob/master/.github/workflows/run-tests.yml#L11

**Comment by owenvoke** [comment]
🤦‍♂ I completely forgot about that, I've added it now. Ah, because they are development branches the tests are failing. 🤔

**Comment by hmazter** [comment]
I have updated composer.json in master to allow `minimum-stability: dev` so you should be able to rebase your branch against master and the test will hopefully pass.

**Comment by owenvoke** [comment]
Thanks @hmazter, rebased and pushed. 👍

**Comment by hmazter** [comment]
v2.1.0 tagged with his included

**Comment by owenvoke** [comment]
Thank you 😀 That's perfect.

**Pull request merged**
